openapi: 3.1.1
info:
  description: ""
  title: upbot API Documentation
  version: 1.0.0
servers:
- url: https://api.upbot.app
security:
- default: []
tags:
- description: |2-

    APIs for managing monitors
  name: Monitor Management
paths:
  /api/monitors:
    get:
      description: ""
      operationId: displayAListingOfTheResource
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/displayAListingOfTheResource_200_response"
          description: ""
      security: []
      summary: Display a listing of the resource.
      tags:
      - Monitor Management
    post:
      description: ""
      operationId: storeANewlyCreatedResourceInStorage
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/storeANewlyCreatedResourceInStorage_request"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/storeANewlyCreatedResourceInStorage_201_response"
          description: ""
      security: []
      summary: Store a newly created resource in storage.
      tags:
      - Monitor Management
  /api/monitors/{id}:
    delete:
      description: Deletes the given monitor if the user is authorized.
      operationId: deleteASpecificMonitor
      parameters:
      - description: The ID of the monitor.
        examples:
          default:
            value: 019875ab-234e-7248-b6db-c37b7e0d8aad
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content:
            text/plain:
              schema:
                type: string
          description: Successful deletion
        "403":
          content:
            text/plain:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            text/plain:
              schema:
                type: string
          description: Not found
      security: []
      summary: Delete a specific monitor.
      tags:
      - Monitor Management
    parameters:
    - description: The ID of the monitor.
      examples:
        default:
          value: 019875ab-234e-7248-b6db-c37b7e0d8aad
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
components:
  schemas:
    displayAListingOfTheResource_200_response_data_inner:
      example:
        avatar_url: avatar_url
        updated_at: updated_at
        bot: bot
        retry_count: 6
        created_at: created_at
        interval: 0
        id: id
        display_name: display_name
        type: type
        target: target
        status: status
      properties:
        id:
          type: string
        display_name:
          type: string
        type:
          type: string
        target:
          type: string
        interval:
          type: integer
        status:
          type: string
        retry_count:
          type: integer
        avatar_url:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        bot:
          type: string
    displayAListingOfTheResource_200_response_links:
      example:
        next: next
        last: last
        prev: prev
        first: first
      properties:
        first:
          type: string
        last:
          type: string
        prev:
          type: string
        next:
          type: string
    displayAListingOfTheResource_200_response_meta:
      example:
        current_page_url: current_page_url
        path: path
        per_page: per_page
        from: 5
        to: 5
        current_page: 1
      properties:
        current_page:
          type: integer
        current_page_url:
          type: string
        from:
          type: integer
        path:
          type: string
        per_page:
          type: string
        to:
          type: integer
    displayAListingOfTheResource_200_response:
      example:
        data:
        - avatar_url: avatar_url
          updated_at: updated_at
          bot: bot
          retry_count: 6
          created_at: created_at
          interval: 0
          id: id
          display_name: display_name
          type: type
          target: target
          status: status
        - avatar_url: avatar_url
          updated_at: updated_at
          bot: bot
          retry_count: 6
          created_at: created_at
          interval: 0
          id: id
          display_name: display_name
          type: type
          target: target
          status: status
        meta:
          current_page_url: current_page_url
          path: path
          per_page: per_page
          from: 5
          to: 5
          current_page: 1
        links:
          next: next
          last: last
          prev: prev
          first: first
      properties:
        data:
          items:
            $ref: "#/components/schemas/displayAListingOfTheResource_200_response_data_inner"
          type: array
        links:
          $ref: "#/components/schemas/displayAListingOfTheResource_200_response_links"
        meta:
          $ref: "#/components/schemas/displayAListingOfTheResource_200_response_meta"
    storeANewlyCreatedResourceInStorage_201_response:
      example:
        id: id
      properties:
        id:
          type: string
    storeANewlyCreatedResourceInStorage_request_bot:
      description: This field is required when <code>type</code> is <code>discord_bot</code>.
      properties:
        discord_bot_id:
          description: "This field is required when <code>type</code> is <code>discord_bot</code>.\
            \ Must match the regex /^\\d{17,19}$/."
          type: string
          nullable: false
        discord_guild_id:
          description: "This field is required when <code>type</code> is <code>discord_bot</code>.\
            \ Must match the regex /^\\d{17,19}$/."
          type: string
          nullable: false
      nullable: false
    storeANewlyCreatedResourceInStorage_request:
      properties:
        name:
          description: This field is required unless <code>type</code> is in <code>discord_bot</code>.
            Must not be greater than 255 characters.
          type: string
          nullable: false
        type:
          description: ""
          enum:
          - discord_bot
          - http
          - ping
          type: string
          nullable: false
        target:
          description: This field is required unless <code>type</code> is in <code>discord_bot</code>.
            Must not be greater than 255 characters.
          type: string
          nullable: false
        retry_count:
          description: This field is required unless <code>type</code> is in <code>discord_bot</code>.
            Must be at least 0. Must not be greater than 10.
          nullable: true
          type: integer
        interval:
          description: This field is required unless <code>type</code> is in <code>discord_bot</code>.
          enum:
          - "30"
          - "60"
          - "120"
          - "300"
          - "600"
          type: string
          nullable: false
        bot:
          $ref: "#/components/schemas/storeANewlyCreatedResourceInStorage_request_bot"
      required:
      - type
  securitySchemes:
    default:
      description: You can retrieve your token by visiting your dashboard and clicking
        <b>Generate API token</b>.
      scheme: bearer
      type: http
